"""
Backtest report generator.
Produces a markdown report from a BacktestResult and writes it to outputs/.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from hermes.backtest.engine import BacktestResult, SetupStats

OUTPUTS_DIR = Path(__file__).parent.parent.parent.parent / "outputs"


def generate_report(result: BacktestResult, output_dir: Path = OUTPUTS_DIR) -> Path:
    """Write a markdown report and return the file path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.utcnow().strftime("%Y-%m-%d")
    filename = f"backtest-report-{result.portfolio}-{ts}.md"
    path = output_dir / filename

    lines = _build_report(result)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _build_report(result: BacktestResult) -> list[str]:
    lines = [
        f"# Hermes Backtest Report — {result.portfolio.upper()} Portfolio",
        "",
        f"**Period:** {result.start_date} → {result.end_date}  ",
        f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**Total trades:** {result.total_trades}",
        "",
        "---",
        "",
    ]

    if not result.setup_stats:
        lines.append("_No trades recorded._")
        return lines

    # ── Overall summary ──────────────────────────────────────
    lines += [
        "## Summary",
        "",
        "| Setup | Trades | Win Rate | Avg PnL% | Avg R:R | Gate |",
        "|-------|--------|----------|----------|---------|------|",
    ]
    for name, s in sorted(result.setup_stats.items()):
        gate = "✅ PASS" if s.passes_gate else "❌ FAIL"
        lines.append(
            f"| {name} | {s.total_trades} | {s.win_rate:.1%} | "
            f"{s.avg_pnl_pct:+.2f}% | {s.avg_rr_realised:.2f} | {gate} |"
        )

    lines += ["", "---", ""]

    # ── Per-setup detail ──────────────────────────────────────
    lines.append("## Per-Setup Detail")
    for name, s in sorted(result.setup_stats.items()):
        lines += _setup_section(name, s)

    # ── Decision gate ─────────────────────────────────────────
    lines += [
        "---",
        "",
        "## Decision Gate",
        "",
        "**Gate criteria:** Win rate ≥ 40%, Avg R:R ≥ 1.0, Trades ≥ 5",
        "",
    ]
    if result.passing_setups:
        lines.append(f"**✅ Approved for live paper trading:** {', '.join(result.passing_setups)}")
    if result.failing_setups:
        lines.append(f"**❌ Killed (insufficient edge):** {', '.join(result.failing_setups)}")

    lines += ["", "---", "", "_Report auto-generated by Hermes BacktestEngine_"]
    return lines


def _setup_section(name: str, s: SetupStats) -> list[str]:
    outcome_breakdown = (
        f"Wins: {s.wins} | Losses: {s.losses} | Expired: {s.expired}"
    )
    gate_note = (
        "✅ Passes gate — approved for live paper trading."
        if s.passes_gate
        else (
            "❌ Fails gate — "
            + (f"win rate {s.win_rate:.1%} < 40%; " if s.win_rate < 0.40 else "")
            + (f"avg R:R {s.avg_rr_realised:.2f} < 1.0; " if s.avg_rr_realised < 1.0 else "")
            + (f"only {s.total_trades} trades (need ≥ 5)" if s.total_trades < 5 else "")
        )
    )
    return [
        "",
        f"### {name}",
        "",
        f"- **Portfolio:** {s.portfolio}",
        f"- **Trades:** {s.total_trades} ({outcome_breakdown})",
        f"- **Win rate:** {s.win_rate:.1%}",
        f"- **Avg PnL:** {s.avg_pnl_pct:+.2f}%",
        f"- **Avg R:R realised:** {s.avg_rr_realised:.2f}",
        "",
        f"> {gate_note}",
        "",
    ]
